### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by jfpios** [cvxgrp/cvxpygen#2]
Thank you for developing this very useful package, which helps me improve the performance of my code. However, I hope it can support more solvers, such as MOSEK. Thank you very much for your work.

**Comment by SteveDiamond** [comment]
Thanks @jfpios ! cvxpy does support mosek. The full list of supported solvers is here: https://www.cvxpy.org/tutorial/advanced/index.html#choosing-a-solver
Instructions for installing solvers are here: https://www.cvxpy.org/install/index.html
