### ISSUE TITLE
SOC dimension issue

### ISSUE THREAD

**Issue by leogrillo** [cvxgrp/cvxpygen#23]
There seems to be an issue with the dimension of the SOC. When passing from a problem with a soc of dimension 100 to 150 I encounter the following problem:

![cvxpygen_soc_issue](https://github.com/cvxgrp/cvxpygen/assets/137873374/60ec9916-3780-4e83-99cd-fb95c0aa0c6a)

**Comment by maxschaller** [comment]
Looks like you need to access `res.cpg_dual.d174`. Please re-open if the issue persists.
