### ISSUE TITLE
Regression with latest upgrade to cvxpy 1.4.0

### ISSUE THREAD

**Issue by zdryan** [cvxgrp/cvxpygen#29]
https://github.com/cvxgrp/cvxpygen/blob/d2a61ae8564742ad288768488d91a11b71fb9458/environment.yml#L9

It appears as though the latest bump to `cvxpy` (`1.3.2` -> `1.4.0`) has introduced a regression in `cvxpygen` (tested on `v0.2.3`) (presumably due to use of its non-public API). In my particular case this manifests as a problem always being dual infeasible (where previously the `osqp` backend would solve successfully).

Would `cvxpygen` be open to pinning the `cvxpy` dependency to an exact version to avoid problems such as these (on new `cvxpy` releases)?

_To circumvent this issue - I have simply pinned both `cvxpy` & `cvxpygen` explicitly._

**Comment by PTNobel** [comment]
Hey zdryan, can you share more info on this problem? Such as a minimized example?

**Comment by maxschaller** [comment]
Thanks @zdryan, this is fixed in version `0.3.0`, also see #30
