### ISSUE TITLE
SDP option in CLARABEL

### ISSUE THREAD

**Issue by estevaoms** [cvxgrp/cvxpygen#35]
Hi,

The Clarabel.cpp project's SDP support is disabled by default, as stated in the README.md file. To enable it, you need to set the CLARABEL_FEATURE_SDP flag to one of the following options:

sdp-accelerate
sdp-netlib
sdp-openblas
sdp-mkl
sdp-r
While modifying the CMakeLists.txt file within the Clarabel.cpp folder inside the cvxpygen folder appears to enable the SDP feature, attempting to compile a cpg_example results in the following error:

/home/vboxuser/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lapack-0.19.0/src/lapack-sys.rs:29385: undefined reference to `ssyevr_'

Despite having blas and lapack installed, this error persists. Resolving this issue is crucial because CLARABEL is currently the only solver capable of handling SDP optimization efficiently in CVXPYGEN.

Thank you for your attention to this matter.

**Comment by estevaoms** [comment]
I was able to resolve the issue by adding the path to the BLAS and LAPACK libraries to the link.txt file in the cpg.example.dir folder. It would be beneficial if CVXPYGEN could generate the link.txt file with the correct path automatically.

**Comment by maxschaller** [comment]
Closing with #38 and `v0.3.1`.
