### ISSUE TITLE
Scalar parameter/variable support

### ISSUE THREAD

**Issue by ldstrohl** [cvxgrp/cvxpygen#4]
Code generation seems to fail for scalar parameters and variables, as opposed to array parameters/variables. For example, suppose we have something like
w_a = cp.Parameter(1,name='w_a')
a = cp.Variable(1,name='a')

objective = cp.Minimize(w*a)

<etc>

This will generate code with errors in both the example and cpg_solve, since the code seems to assume each parameter and variable is an array. The cpg_example will call cpg_update_w(0, w_value), but the cpg_update_w function only accepts one argument. Similarly, cpg_solve->cpg_retrieve_prim() will attempt to assign CPG_Prim.a = ecos_workspace[k], which will throw an error: incompatible types when assigning to type ‘c_float *’ {aka ‘double *’} from type ‘pfloat’ {aka ‘double’}

Is there a simple way to deal with this (e.g. some scalar=True flag)? A workaround might be to make all scalars arrays of length 2 and only use the first index, but obviously that's not desirable.

Edit: 
A better reproduction is to set n=1 in the network.ipynb example. This will give the same kind of error.

**Comment by SteveDiamond** [comment]
@maxschaller

**Comment by maxschaller** [comment]
Good catch! To make it work immediately, simply omit the first argument when constructing your variable and write `a = cp.Variable(name='a')`.

`cvxpygen` has been tested for variables with squeezed representation. When constructing a `cvxpy` variable by passing `1` as first positional argument, it will be of shape `(1,)`, a vector of length 1 and not a scalar (the squeezed representation). 

I will make sure that non-squeezed representations of variables work as well. Non-squeezed representations of parameters should already work.

**Comment by ldstrohl** [comment]
Awesome, easy fix, confirmed it works on my application.

Thank you!
