### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by scout222** [cvxgrp/cvxpygen#6]
Thank you for creating this repository! I was keen on trying it out, but I always get an import error in line 12
`from nonneg_LS import cpg_module
` of the file `cpg_solver.py`

As far as I could track the error down, it seems like the Pybind rountine isn't working, as the `cpg_module`  is generated from the C++ files. 

Has anyone else had this error? It looks like a common Python problem but I don't seem to find a solution.

Thanks in advance

**Comment by maxschaller** [comment]
Please share a (minimal) example for reproducibility - thanks!

**Comment by maxschaller** [comment]
@scout222 this is fixed in the latest release `0.2.2` (via #17).
