### ISSUE TITLE
Code generation with OSQP fails

### ISSUE THREAD

**Issue by chenyx09** [cvxgrp/cvxpygen#7]
Code generation with OSQP fails with error "undefined symbol: osqp_update_verbose". It seems that osqp_update_verbose is not defined in osqp.h when EMBEDDED is set. Can anyone fix this? Thanks!

**Comment by mmusallam19** [comment]
Hey @chenyx09 Is there a specific example or code you were working with when you got this error? If so, can you share it please?

**Comment by ilyanoskov** [comment]
I am having the same issue.

Solver setting "verbose" not available

**Comment by ilyanoskov** [comment]
I am also getting an error that the setting "polish" is not available for the OSQP solver. Would it be possible to add it?

**Comment by PTNobel** [comment]
Hello @ilyanoskov, do you have an example of the code that is failing you could share?

**Comment by ilyanoskov** [comment]
Hi @PTNobel, thanks a lot for looking into this, I set the value `polish=True` here:

![CleanShot 2023-03-24 at 23 49 25@2x](https://user-images.githubusercontent.com/16443383/227663446-1cf92b52-aca8-44e3-89b3-c9e86ae8da05.png)

Which I take from https://github.com/cvxgrp/cvxpygen/blob/master/examples/portfolio.ipynb

**Comment by ilyanoskov** [comment]
Hi @PTNobel, thanks a lot for looking into this. 

I add `polish=True` here:
https://github.com/cvxgrp/cvxpygen/blob/master/examples/portfolio.ipynb
![CleanShot 2023-03-24 at 23 54 04@2x](https://user-images.githubusercontent.com/16443383/227663710-96c258e5-e618-4ef4-85c9-5168b71395ad.png)

And it fails for me with the following error:

```
AttributeError                            Traceback (most recent call last)
~/coding/cvxpygen/examples/portfolio_code/cpg_solver.py in cpg_solve(prob, updated_params, **kwargs)
     30         try:
---> 31             eval('cpg_module.set_solver_%s(value)' % key)
     32         except AttributeError:

~/coding/cvxpygen/examples/portfolio_code/cpg_solver.py in <module>

AttributeError: module 'portfolio_code.cpg_module' has no attribute 'set_solver_polish'
```

**Comment by PTNobel** [comment]
This seems unrelated to the undefined symbol error from the top of the thread. Please open a new issue with your feature request.

**Comment by ilyanoskov** [comment]
Sure, will do, although when I set `verbose=True` I get the same error:

```
val = prob.solve(method='CPG', verbose=True)
```

```
AttributeError                            Traceback (most recent call last)
~/coding/cvxpygen/examples/portfolio_code/cpg_solver.py in cpg_solve(prob, updated_params, **kwargs)
     30         try:
---> 31             eval('cpg_module.set_solver_%s(value)' % key)
     32         except AttributeError:

~/coding/cvxpygen/examples/portfolio_code/cpg_solver.py in <module>
```

**Comment by PTNobel** [comment]
I believe that CVXPYgen does not support passing attributes to the solvers, so please file a feature request for that. These both seem unrelated to the linking issue when EMBEDDED is set.

**Comment by maxschaller** [comment]
Setting verbose with OSQP was previously not possible by design. I assume that you directly accessed the OSQP interface and invoked `osqp_update_verbose` (which then obviously failed).

Anyways, setting verbose with OSQP is now supported (as of #18 and version `0.2.3`)! At code generation time, you need to add `enable_settings=['verbose']` when calling `generate_code`.
